// terminal

package lib

const (
	TERMINAL_TYPE_UNKNOWN      = 0
	TERMINAL_TYPE_PC           = 1
	TERMINAL_TYPE_FEATUREPHONE = 2
	TERMINAL_TYPE_SMARTPHONE   = 3
	TERMINAL_TYPE_ANDROID_APP  = 4
	TERMINAL_TYPE_IOS_APP      = 5
)
